//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cllearworks.COH.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRequest
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string GmcId { get; set; }
        public string ApnId { get; set; }
        public string Email { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public int Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
