//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cllearworks.COH.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayDetail
    {
        public int Id { get; set; }
        public int HolidayId { get; set; }
        public Nullable<int> ToClient { get; set; }
        public Nullable<int> ToPlace { get; set; }
        public Nullable<int> ToDepartment { get; set; }
        public Nullable<int> ToEmployee { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Department Department { get; set; }
        public virtual Holiday Holiday { get; set; }
        public virtual Place Place { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
