//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cllearworks.COH.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int Id { get; set; }
        public int AttendanceId { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public Nullable<bool> IsIn { get; set; }
        public Nullable<bool> IsOut { get; set; }
        public Nullable<long> TrackDuration { get; set; }
        public int FromBeacon { get; set; }
        public string Status { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual Beacon Beacon { get; set; }
    }
}
